# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e78dedba8cc5b5ad0cce9ec4854a128371193d87fe840abf98171478401d952db41c7034e49d46255b4e9eac6bf458ea7817e7dd52631245b1d9b288d9b6bd43

test:
  secret_key_base: 03f866eabf8c0491ca181435caf0ef5c00d768592dfce69177e50c12d22360483956dd1d5aef91f50f5c1f36945ac3e3406ee5f6394e98b76a3e7f2975e003dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
